DROP TABLE IF EXISTS `pm_metrics`;

CREATE TABLE IF NOT EXISTS `pm_metrics` (

  `name` VARCHAR(255) NOT NULL UNIQUE,
  `weight` INT NOT NULL DEFAULT 100,
  `scale` INT NOT NULL DEFAULT 10,

  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `creation_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP

) AUTO_INCREMENT=1;
